modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="destiny_loc"
version="1.0.184"
displayName="Destiny LoC"
credits="Vanilla"
displayURL="https://twitter.com/Vanilla_JP"
logoFile="logo.png"
authors="Vanilla"
description='''
for Light our Craft Server Mods
'''

[[dependencies.destiny_loc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




